[package]
name = "iron_web_demo"
version = "0.1.0"
authors = ["u"]

[dependencies]
iron="*"
time="*"
postgres="*"
r2d2_postgres="*"
r2d2="*"
router="*"
mount = "*"
staticfile="*"
handlebars-iron="*"
rustc-serialize = "*"
persistent="*"
hyper="*"
